# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5          # Number of pages in the pagination links
    default_options:
        page_name: page    # Name of the query parameter
        sort_field_name: sort  # Name of the sort field query parameter
        sort_direction_name: direction  # Name of the sort direction query parameter
        distinct: true     # Ensure distinct results, set to false for performance
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'  # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'  # sort link template

